### PR TITLE
Bump versions sinatra + rack versions for example_server

### PR DESCRIPTION
**Pull request by benoittgt**

### CODE REVIEW

**Comment by utilum** [comment]
What do we use Sinatra for?

**Comment by utilum** [comment]
I mean: what's the example server's responsibility?

**Review by utilum — APPROVED** [review]
Change seems clean and simple... Nothing dramatic in the changelings... just wish I knew how we use these to imagine impact.

**Comment by RobertAudi** [comment]
@utilum The example server is not part of the gem, even though it's shipped with it. So that change does not affect the gem itself, but rather the example implementation that uses the gem.

**Pull request merged**
